name: Daily Webpage Check

# Run once per day at 00:00 UTC (adjust the cron as needed)
on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch: {}

jobs:
  check-element:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run the check script
        env:
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: |
          python3 scrape.py
